// The design houses Amoria's Inspired Perfume line draws from — powers
// the homepage's brand-logo grid and each brand's own /brand/[slug] page.
// `designHouse` is the exact Product.designHouse string set at import time
// (see backend/prisma/import-real-catalog.ts — "Inspired by <BRAND>", taken
// verbatim from the source sheet's own BRAND column) and is what each
// brand page filters products by; it's null for brands whose logo we have
// but that don't have any matching products yet.
export interface Brand {
  name: string;
  slug: string;
  logo: string;
  designHouse: string | null;
}

export const BRANDS: Brand[] = [
  { name: "Afnan", slug: "afnan", logo: `/brands/afnan.png`, designHouse: "Inspired by Afnan" },
  { name: "Ahmed Al Maghribi", slug: "ahmed-al-maghribi", logo: `/brands/ahmed-al-maghribi.png`, designHouse: "Inspired by Ahmed Al Maghribi" },
  { name: "Ajmal", slug: "ajmal", logo: `/brands/ajmal.png`, designHouse: "Inspired by Ajmal" },
  { name: "Al Jazeera Perfumes", slug: "al-jazeera-perfumes", logo: `/brands/al-jazeera-perfumes.png`, designHouse: "Inspired by Al Jazeera" },
  { name: "Amouage", slug: "amouage", logo: `/brands/amouage.png`, designHouse: "Inspired by Amouage" },
  { name: "Arabian Oud", slug: "arabian-oud", logo: `/brands/arabian-oud.png`, designHouse: null },
  { name: "Atelier Des Ors", slug: "atelier-des-ors", logo: `/brands/atelier-des-ors.png`, designHouse: "Inspired by Atelier Des Ors" },
  { name: "Azzaro", slug: "azzaro", logo: `/brands/azzaro.png`, designHouse: "Inspired by Azzaro" },
  { name: "BDK Parfums", slug: "bdk-parfums", logo: `/brands/bdk-parfums.png`, designHouse: "Inspired by BDK Parfums" },
  { name: "Burberry", slug: "burberry", logo: `/brands/burberry.png`, designHouse: "Inspired by Burberry" },
  { name: "Bvlgari", slug: "bvlgari", logo: `/brands/bvlgari.png`, designHouse: "Inspired by Bvlgari" },
  { name: "Byredo", slug: "byredo", logo: `/brands/byredo.png`, designHouse: "Inspired by Byredo" },
  { name: "Carolina Herrera", slug: "carolina-herrera", logo: `/brands/carolina-herrera.png`, designHouse: "Inspired by Carolina Herrera (CH)" },
  { name: "Cartier", slug: "cartier", logo: `/brands/cartier.png`, designHouse: "Inspired by Cartier" },
  { name: "Casamorati", slug: "casamorati", logo: `/brands/casamorati.png`, designHouse: "Inspired by Casamorati" },
  { name: "Chanel", slug: "chanel", logo: `/brands/chanel.png`, designHouse: "Inspired by Chanel" },
  { name: "Chloé", slug: "chloe", logo: `/brands/chloe.png`, designHouse: null },
  { name: "Chopard", slug: "chopard", logo: `/brands/chopard.png`, designHouse: null },
  { name: "Calvin Klein", slug: "calvin-klein", logo: `/brands/calvin-klein.png`, designHouse: "Inspired by Calvin Klein" },
  { name: "Clive Christian", slug: "clive-christian", logo: `/brands/clive-christian.png`, designHouse: "Inspired by Clive Christian" },
  { name: "Creed", slug: "creed", logo: `/brands/creed.png`, designHouse: "Inspired by Creed" },
  { name: "Davidoff", slug: "davidoff", logo: `/brands/davidoff.png`, designHouse: "Inspired by Davidoff" },
  { name: "Designer Sheikh", slug: "designer-sheikh", logo: `/brands/designer-sheikh.png`, designHouse: null },
  { name: "Dior", slug: "dior", logo: `/brands/dior.png`, designHouse: "Inspired by Dior" },
  { name: "Diptyque", slug: "diptyque", logo: `/brands/diptyque.png`, designHouse: "Inspired by Diptyque" },
  { name: "DKNY", slug: "dkny", logo: `/brands/dkny.png`, designHouse: "Inspired by DKNY" },
  { name: "Dolce & Gabbana", slug: "dolce-gabbana", logo: `/brands/dolce-gabbana.png`, designHouse: "Inspired by D&G (Dolce & Gabbana)" },
  { name: "Dunhill", slug: "dunhill", logo: `/brands/dunhill.png`, designHouse: "Inspired by Dunhill" },
  { name: "Escada", slug: "escada", logo: `/brands/escada.png`, designHouse: "Inspired by Escada" },
  { name: "Essential Parfums", slug: "essential-parfums", logo: `/brands/essential-parfums.png`, designHouse: "Inspired by Essential Parfums" },
  { name: "État Libre d'Orange", slug: "etat-libre-dorange", logo: `/brands/etat-libre-dorange.png`, designHouse: "Inspired by État Libre d'Orange (EL)" },
  { name: "Ex Nihilo", slug: "ex-nihilo", logo: `/brands/ex-nihilo.png`, designHouse: "Inspired by Ex Nihilo" },
  { name: "Fendi", slug: "fendi", logo: `/brands/fendi.png`, designHouse: "Inspired by Fendi" },
  { name: "Frederic Malle", slug: "frederic-malle", logo: `/brands/frederic-malle.png`, designHouse: "Inspired by Frederic Malle (FM)" },
  { name: "Giardini Di Toscana", slug: "giardini-di-toscana", logo: `/brands/giardini-di-toscana.png`, designHouse: "Inspired by Giardini Di Toscana" },
  { name: "Giorgio Armani", slug: "giorgio-armani", logo: `/brands/giorgio-armani.png`, designHouse: "Inspired by Armani (Giorgio Armani)" },
  { name: "Gissah", slug: "gissah", logo: `/brands/gissah.png`, designHouse: "Inspired by Gissah" },
  { name: "Givenchy", slug: "givenchy", logo: `/brands/givenchy.png`, designHouse: "Inspired by Givenchy" },
  { name: "Gucci", slug: "gucci", logo: `/brands/gucci.png`, designHouse: "Inspired by Gucci" },
  { name: "Guerlain", slug: "guerlain", logo: `/brands/guerlain.png`, designHouse: "Inspired by Guerlain" },
  { name: "Hugo Boss", slug: "hugo-boss", logo: `/brands/hugo-boss.png`, designHouse: "Inspired by Hugo Boss" },
  { name: "Initio Parfums Privés", slug: "initio-parfums-prives", logo: `/brands/initio-parfums-prives.png`, designHouse: "Inspired by INITIO Parfums Privés (IPP)" },
  { name: "Issey Miyake", slug: "issey-miyake", logo: `/brands/issey-miyake.png`, designHouse: null },
  { name: "Jean Paul Gaultier", slug: "jean-paul-gaultier", logo: `/brands/jean-paul-gaultier.png`, designHouse: "Inspired by Jean Paul Gaultier (JPG)" },
  { name: "Kajal", slug: "kajal", logo: `/brands/kajal.png`, designHouse: "Inspired by Kajal" },
  { name: "Kayali", slug: "kayali", logo: `/brands/kayali.png`, designHouse: "Inspired by Kayali" },
  { name: "Kenzo", slug: "kenzo", logo: `/brands/kenzo.png`, designHouse: null },
  { name: "Kilian", slug: "kilian", logo: `/brands/kilian.png`, designHouse: "Inspired by Kilian" },
  { name: "Lalique", slug: "lalique", logo: `/brands/lalique.png`, designHouse: "Inspired by Lalique" },
  { name: "Lancôme", slug: "lancome", logo: `/brands/lancome.png`, designHouse: "Inspired by Lancôme" },
  { name: "Lattafa", slug: "lattafa", logo: `/brands/lattafa.png`, designHouse: "Inspired by Lattafa" },
  { name: "Le Labo", slug: "le-labo", logo: `/brands/le-labo.png`, designHouse: "Inspired by Le Labo" },
  { name: "Louis Vuitton", slug: "louis-vuitton", logo: `/brands/louis-vuitton.png`, designHouse: "Inspired by Louis Vuitton (LV)" },
  { name: "Maison Crivelli", slug: "maison-crivelli", logo: `/brands/maison-crivelli.png`, designHouse: "Inspired by Maison Crivelli (MC)" },
  { name: "Maison Francis Kurkdjian", slug: "maison-francis-kurkdjian", logo: `/brands/maison-francis-kurkdjian.png`, designHouse: "Inspired by Maison Francis Kurkdjian (MFK)" },
  { name: "Maison Margiela", slug: "maison-margiela", logo: `/brands/maison-margiela.png`, designHouse: "Inspired by Maison Margiela" },
  { name: "Mancera", slug: "mancera", logo: `/brands/mancera.png`, designHouse: "Inspired by Mancera" },
  { name: "Marc-Antoine Barrois", slug: "marc-antoine-barrois", logo: `/brands/marc-antoine-barrois.png`, designHouse: "Inspired by Marc-Antoine Barrois" },
  { name: "Matiere Premiere", slug: "matiere-premiere", logo: `/brands/matiere-premiere.png`, designHouse: "Inspired by Matiere Premiere (MP)" },
  { name: "Mont Blanc", slug: "mont-blanc", logo: `/brands/mont-blanc.png`, designHouse: null },
  { name: "Montale", slug: "montale", logo: `/brands/montale.png`, designHouse: "Inspired by Montale" },
  { name: "Nasomatto", slug: "nasomatto", logo: `/brands/nasomatto.png`, designHouse: "Inspired by Nasomatto" },
  { name: "Nina Ricci", slug: "nina-ricci", logo: `/brands/nina-ricci.png`, designHouse: null },
  { name: "Nishane", slug: "nishane", logo: `/brands/nishane.png`, designHouse: "Inspired by Nishane" },
  { name: "Ormonde Jayne", slug: "ormonde-jayne", logo: `/brands/ormonde-jayne.png`, designHouse: null },
  { name: "Orto Parisi", slug: "orto-parisi", logo: `/brands/orto-parisi.png`, designHouse: "Inspired by Orto Parisi (OTP)" },
  { name: "Paco Rabanne", slug: "paco-rabanne", logo: `/brands/paco-rabanne.png`, designHouse: "Inspired by Paco Rabanne" },
  { name: "Parfums De Marly", slug: "parfums-de-marly", logo: `/brands/parfums-de-marly.png`, designHouse: "Inspired by Parfums de Marly" },
  { name: "Penhaligon's", slug: "penhaligons", logo: `/brands/penhaligons.png`, designHouse: "Inspired by Penhaligon's" },
  { name: "Prada", slug: "prada", logo: `/brands/prada.png`, designHouse: "Inspired by Prada" },
  { name: "Ralph Lauren", slug: "ralph-lauren", logo: `/brands/ralph-lauren.png`, designHouse: "Inspired by Ralph Lauren" },
  { name: "Roberto Cavalli", slug: "roberto-cavalli", logo: `/brands/roberto-cavalli.png`, designHouse: "Inspired by Roberto Cavalli" },
  { name: "Roja Parfums", slug: "roja-parfums", logo: `/brands/roja-parfums.png`, designHouse: "Inspired by Roja Parfums" },
  { name: "Sospiro", slug: "sospiro", logo: `/brands/sospiro.png`, designHouse: "Inspired by Sospiro" },
  { name: "Stéphane Humbert Lucas", slug: "stephane-humbert-lucas", logo: `/brands/stephane-humbert-lucas.png`, designHouse: "Inspired by Stéphane Humbert Lucas (SHL 777)" },
  { name: "Thierry Mugler", slug: "thierry-mugler", logo: `/brands/thierry-mugler.png`, designHouse: "Inspired by Thierry Mugler" },
  { name: "Thomas Kosmala", slug: "thomas-kosmala", logo: `/brands/thomas-kosmala.png`, designHouse: "Inspired by Thomas Kosmala" },
  { name: "Tiziana Terenzi", slug: "tiziana-terenzi", logo: `/brands/tiziana-terenzi.png`, designHouse: "Inspired by Tiziana Terenzi" },
  { name: "Tom Ford", slug: "tom-ford", logo: `/brands/tom-ford.png`, designHouse: "Inspired by Tom Ford" },
  { name: "Tommy Hilfiger", slug: "tommy-hilfiger", logo: `/brands/tommy-hilfiger.png`, designHouse: null },
  { name: "Unique'e Luxury", slug: "uniquee-luxury", logo: `/brands/uniquee-luxury.png`, designHouse: null },
  { name: "Valentino", slug: "valentino", logo: `/brands/valentino.png`, designHouse: null },
  { name: "Van Cleef & Arpels", slug: "van-cleef-arpels", logo: `/brands/van-cleef-arpels.png`, designHouse: null },
  { name: "Versace", slug: "versace", logo: `/brands/versace.png`, designHouse: null },
  { name: "Victoria's Secret", slug: "victorias-secret", logo: `/brands/victorias-secret.png`, designHouse: null },
  { name: "Viktor & Rolf", slug: "viktor-rolf", logo: `/brands/viktor-rolf.png`, designHouse: null },
  { name: "Vilhelm Parfumerie", slug: "vilhelm-parfumerie", logo: `/brands/vilhelm-parfumerie.png`, designHouse: null },
  { name: "Xerjoff", slug: "xerjoff", logo: `/brands/xerjoff.png`, designHouse: null },
  { name: "Yves Saint Laurent", slug: "yves-saint-laurent", logo: `/brands/yves-saint-laurent.png`, designHouse: null },
];

export function getBrandBySlug(slug: string): Brand | undefined {
  return BRANDS.find((b) => b.slug === slug);
}
